author:
  - name: Gamaliel
  - lastname: Churata
  - wiki: https://es.wikipedia.org/wiki/Gamaliel_Churata
title: El pez de oro
subtitle: Retablos del Laykhakuy
epub: https://github.com/neoenanos/pez-de-oro
language: Spanish

