name: Release and Deploy

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: | 
          sudo apt install -y --fix-missing make pandoc qpdf latexmk texlive-xetex texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended rename
        
      - name: Compile all
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/*"
          generate_release_notes: true

      - name: Rename html
        run: mv build/html/book.html build/html/index.html

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './build/html'
          production-branch: main
          netlify-config-path: ./netlify.toml
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1