name: Release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pandoc
        run: sudo apt install -y pandoc
        
      - name: Get epub name
        id: epub_filename
        run: |
          title=$(grep '^title:' meta/metadata.yml | cut -d ' ' -f2- | xargs)
          author_name=$(grep '^  - name:' meta/metadata.yml | cut -d ':' -f2- | xargs)
          author_lastname=$(grep '^  - lastname:' meta/metadata.yml | cut -d ':' -f2- | xargs)
          filename="$author_lastname, $author_name - $title"
          echo "filename=${filename// /_}" >> $GITHUB_OUTPUT

      - name: Compile Epub
        run: |
          mkdir -p out
          pandoc md/* \
          -o "out/${{steps.epub_filename.outputs.filename}}.epub" \
          --metadata-file=meta/metadata.yml \
          --toc-depth 2 

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: "out/*"
          generate_release_notes: true